[package]
name = "musande-applications"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "S-entropy applications and examples"

[dependencies]
musande-core = { workspace = true } 